# Generated by Django 3.2.19 on 2024-12-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_user_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('Korygujące', 'Korygujące'), ('Rozwijające', 'Rozwijające'), ('Podstawa', 'Podstawa'), ('Rozszerzenie', 'Rozszerzenie'), ('Podstawa i rozszerzenie', 'Podstawa i rozszerzenie')], max_length=50, verbose_name='Poziom'),
        ),
    ]
