# Generated by Django 3.2.19 on 2024-12-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_user_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created', '-updated'], 'verbose_name': 'Posty - Strefa Wiedzy', 'verbose_name_plural': 'Posty - Strefa Wiedzy'},
        ),
    ]
