# Generated by Django 3.2.19 on 2024-12-17 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Posty - Strefa Wiedzy', 'verbose_name_plural': 'Posty - Strefa Wiedzy'},
        ),
    ]
