# Generated by Django 3.2.19 on 2024-12-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20241219_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstats',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
