# Generated by Django 3.2.19 on 2024-12-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_user_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
