# Generated by Django 3.2.19 on 2024-12-25 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_user_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstats',
            name='all_referral_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonstats',
            name='month_referral_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='level',
            field=models.CharField(choices=[('basic', 'Podstawowy'), ('advanced', 'Rozszerzony')], default='basic', max_length=10),
        ),
        migrations.CreateModel(
            name='NewStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('Podstawa', 'Podstawa'), ('Rozszerzenie', 'Rozszerzenie')], max_length=50, verbose_name='Poziom')),
                ('is_selected', models.BooleanField(default=False, verbose_name='Czy wybrany?')),
                ('is_new', models.BooleanField(default=True, verbose_name='Czy nowy?')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.topic', verbose_name='Przedmiot')),
            ],
        ),
    ]
