# Generated by Django 3.2.19 on 2025-01-01 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20241229_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudents',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.AlterField(
            model_name='teachersearning',
            name='month',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='teachersearning',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
