# Generated by Django 3.2.19 on 2025-01-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20250101_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudents',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
