# Generated by Django 5.1.4 on 2025-01-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_alter_newstudents_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='level',
            field=models.CharField(choices=[('basic', 'Podstawa'), ('advanced', 'Rozszerzenie')], default='basic', max_length=10),
        ),
    ]
