# Generated by Django 5.1.4 on 2025-01-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_alter_room_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-courseCreated'], 'verbose_name': 'Kursy - Strefa Korepetycji', 'verbose_name_plural': 'Kursy - Strefa Korepetycji'},
        ),
        migrations.AlterModelOptions(
            name='newstudents',
            options={'verbose_name': 'Nowi uczniowie - Strefa Korepetycji', 'verbose_name_plural': 'Nowi uczniowie - Strefa Korepetycji'},
        ),
    ]
