# Generated by Django 5.1.4 on 2025-01-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_alter_course_options_alter_newstudents_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemessage',
            options={'ordering': ['-messageUpdated', '-messageCreated'], 'verbose_name': 'Komentarze - Strefa Korepetycji', 'verbose_name_plural': 'Komentarze - Strefa Korepetycji'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-postUpdated', '-postCreated'], 'verbose_name': 'Lekcje - Strefa Korepetycji', 'verbose_name_plural': 'Lekcje - Strefa Korepetycji'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='payment',
            field=models.IntegerField(default=0),
        ),
    ]
