# Generated by Django 5.1.4 on 2025-02-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_alter_coursemessage_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='add_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teachersearning',
            name='month',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
